/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacemath;

/**
 *
 * @author romain.faure
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_uniforme = new javax.swing.JButton();
        btn_normale = new javax.swing.JButton();
        btn_discrete = new javax.swing.JButton();
        btn_binomiale = new javax.swing.JButton();
        btn_expo = new javax.swing.JButton();
        btn_quitter = new javax.swing.JButton();
        lb_titre = new javax.swing.JLabel();
        background_image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(620, 540));

        jPanel1.setLayout(null);

        btn_uniforme.setBackground(new java.awt.Color(0, 153, 0));
        btn_uniforme.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_uniforme.setText("loi uniforme discrète");
        btn_uniforme.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_uniforme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_uniformeActionPerformed(evt);
            }
        });
        jPanel1.add(btn_uniforme);
        btn_uniforme.setBounds(140, 130, 340, 31);

        btn_normale.setBackground(new java.awt.Color(0, 153, 0));
        btn_normale.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_normale.setText("loi normale");
        btn_normale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_normaleActionPerformed(evt);
            }
        });
        jPanel1.add(btn_normale);
        btn_normale.setBounds(140, 370, 340, 31);

        btn_discrete.setBackground(new java.awt.Color(0, 153, 0));
        btn_discrete.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_discrete.setText("loi discrète sur ensemble fini");
        btn_discrete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_discreteActionPerformed(evt);
            }
        });
        jPanel1.add(btn_discrete);
        btn_discrete.setBounds(140, 250, 340, 31);

        btn_binomiale.setBackground(new java.awt.Color(0, 153, 0));
        btn_binomiale.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_binomiale.setText("loi binomiale");
        btn_binomiale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_binomialeActionPerformed(evt);
            }
        });
        jPanel1.add(btn_binomiale);
        btn_binomiale.setBounds(140, 190, 340, 31);

        btn_expo.setBackground(new java.awt.Color(0, 153, 0));
        btn_expo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_expo.setText("loi exponentielle ");
        btn_expo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_expoActionPerformed(evt);
            }
        });
        jPanel1.add(btn_expo);
        btn_expo.setBounds(140, 310, 340, 31);

        btn_quitter.setBackground(new java.awt.Color(0, 153, 0));
        btn_quitter.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_quitter.setText("Quitter");
        btn_quitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quitterActionPerformed(evt);
            }
        });
        jPanel1.add(btn_quitter);
        btn_quitter.setBounds(250, 450, 120, 31);

        lb_titre.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        lb_titre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_titre.setText("Probabilités et Statistique");
        jPanel1.add(lb_titre);
        lb_titre.setBounds(0, 0, 620, 140);

        background_image.setIcon(new javax.swing.ImageIcon("Z:\\javanetbeans\\interfaceMATH\\depositphotos_160456734-stock-photo-green-blackboard-with-math-formula.jpg")); // NOI18N
        jPanel1.add(background_image);
        background_image.setBounds(-2, -6, 630, 520);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_uniformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_uniformeActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_loiUniformeDiscrete().setVisible(true);              
            }
        });
    }//GEN-LAST:event_btn_uniformeActionPerformed

    private void btn_discreteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_discreteActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_loiDiscrete().setVisible(true);              
            }
        });
    }//GEN-LAST:event_btn_discreteActionPerformed

    private void btn_quitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quitterActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_quitterActionPerformed

    private void btn_expoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_expoActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_loiExponentielle().setVisible(true);              
            }
        });
    }//GEN-LAST:event_btn_expoActionPerformed

    private void btn_binomialeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_binomialeActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_loiBinomiale().setVisible(true);              
            }
        });
    }//GEN-LAST:event_btn_binomialeActionPerformed

    private void btn_normaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_normaleActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_loiNormale().setVisible(true);              
            }
        });
    }//GEN-LAST:event_btn_normaleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true); 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background_image;
    private javax.swing.JButton btn_binomiale;
    private javax.swing.JButton btn_discrete;
    private javax.swing.JButton btn_expo;
    private javax.swing.JButton btn_normale;
    private javax.swing.JButton btn_quitter;
    private javax.swing.JButton btn_uniforme;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_titre;
    // End of variables declaration//GEN-END:variables
}
